DISCORD_TOKEN: "MTMyNzk0NzY5NTUzMjUzOTk4Ng.Gb6FFh.rsPPYNFLYRMCU2l4xfwCkAyqgY0UN-wMzZQTxI" #input your discord token here
FF-PATH: ["C:/ffmpeg/bin/ffmpeg.exe", "/usr/local/bin/ffmpeg"] ##chane ffmpeg location first for windows, second for linux
PREFIX: "." ##change to your preffered
idle: 5